### ISSUE TITLE
Output is pure noise

### ISSUE THREAD

**Issue by federicocost** [sony/diffiner#2]
When I try running the diffiner with default settings, the result I get is almost pure noise. My setup is python 3.8.18, pytorch 1.10.2+cu111. I am only running the example with the pretrained model linked on github

**Comment by r-sawata** [comment]
Hi, sorry for my late. 

Let me confirm. Did you run `./run_example.sh` as I wrote in the doc? If so, could you paste its log (output) here?

**Comment by federicocost** [comment]
Don't worry, I solved it.

**Comment by r-sawata** [comment]
Good to know. Thanks.
